language: node_js
node_js:
  - 16
jobs:
  include:
    - stage: Build
      name: Webpack compile
      script: NODE_ENV=production yarn run build
    - stage: Lint
      name: ESLint run
      script: yarn lint
    - stage: Tests
      name: Unit tests
      script: yarn test
